export const FETCH_TOUR_DETAILS_REQUEST = 'FETCH_TOUR_DETAILS_REQUEST';
export const FETCH_TOUR_DETAILS_SUCCESS = 'FETCH_TOUR_DETAILS_SUCCESS';
export const FETCH_TOUR_DETAILS_FAILURE = 'FETCH_TOUR_DETAILS_FAILURE';
